services:
  mongodb:
    image: mongo:7
    container_name: repositories-cache-mongodb-dev
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data_dev:/data/db
    environment:
      - MONGO_INITDB_DATABASE=repositories_cache
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/repositories_cache --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  mongodb_data_dev:
